version: "3.7"

services:
  frontend:
    image: frontend
    container_name: wildfire_website
    build: ./frontend
    expose:
      - 8080
    volumes:
      - './frontend:/frontend'
    networks:
      - vlan
    ports:
      - 8080:8080

networks:
  vlan: